apiVersion: v1
kind: Service
metadata:
  name: rubintv
  labels:
    app: rubintv
spec:
  ports:
    - name: rubintv-http
      protocol: TCP
      port: 8080
      targetPort: app
  selector:
    name: rubintv
